# Generated by Django 6.0.6 on 2026-06-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple : Informatique, Sciences Comptables, Génie Civil', max_length=100, verbose_name='Nom du département')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code court')),
            ],
            options={
                'verbose_name': 'Département',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Quel objet proposez-vous ?', max_length=200)),
                ('description', models.TextField(help_text="Décrivez l'état du matériel, l'édition (si livre), etc.", max_length=1000)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, help_text="Laissez à 0.00 si c'est un don ou un prêt", max_digits=6)),
                ('nature', models.CharField(choices=[('DON', 'Don (Gratuit)'), ('PRET', 'Prêt temporaire'), ('VENTE', 'Vente à prix réduit')], default='DON', help_text="Nature de l'échange", max_length=5)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('categories', models.ManyToManyField(help_text='Sélectionnez une ou plusieurs catégories', to='annonces.categorie')),
                ('departement', models.ForeignKey(blank=True, help_text='Filière particulièrement concernée par ce matériel (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.departement')),
            ],
            options={
                'verbose_name': 'Annonce',
                'ordering': ['-date_publication'],
            },
        ),
    ]
